/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.CoursesController;
import Models.CoursesDbModel;
import Models.DatabaseModel;

/**
 *
 * @author gurkay
 */
public class JInternalFrameCoursesAdd extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameCoursesAdd
     */
    public JInternalFrameCoursesAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRecordButtonSet = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlCoursesInfo = new javax.swing.JPanel();
        lblCoursesId = new javax.swing.JLabel();
        lblCoursesName = new javax.swing.JLabel();
        txtCoursesName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtCoursesCredit = new javax.swing.JTextField();
        lblCoursesCode = new javax.swing.JLabel();
        txtCoursesCode = new javax.swing.JTextField();

        setClosable(true);

        pnlRecordButtonSet.setBackground(new java.awt.Color(244, 130, 17));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");

        btnDelete.setText("Delete");

        javax.swing.GroupLayout pnlRecordButtonSetLayout = new javax.swing.GroupLayout(pnlRecordButtonSet);
        pnlRecordButtonSet.setLayout(pnlRecordButtonSetLayout);
        pnlRecordButtonSetLayout.setHorizontalGroup(
            pnlRecordButtonSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordButtonSetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlRecordButtonSetLayout.setVerticalGroup(
            pnlRecordButtonSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordButtonSetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecordButtonSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCoursesInfo.setBackground(new java.awt.Color(222, 171, 123));

        lblCoursesId.setText("Courses Id");

        lblCoursesName.setText("Courses Name");

        lblLastName.setText("Courses Credit");

        lblCoursesCode.setText("Courses Code");

        javax.swing.GroupLayout pnlCoursesInfoLayout = new javax.swing.GroupLayout(pnlCoursesInfo);
        pnlCoursesInfo.setLayout(pnlCoursesInfoLayout);
        pnlCoursesInfoLayout.setHorizontalGroup(
            pnlCoursesInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoursesInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCoursesInfoLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(txtCoursesName))
                    .addGroup(pnlCoursesInfoLayout.createSequentialGroup()
                        .addGroup(pnlCoursesInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCoursesId)
                            .addComponent(lblCoursesName)
                            .addGroup(pnlCoursesInfoLayout.createSequentialGroup()
                                .addComponent(lblLastName)
                                .addGap(56, 56, 56)
                                .addComponent(txtCoursesCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 177, Short.MAX_VALUE))
                    .addGroup(pnlCoursesInfoLayout.createSequentialGroup()
                        .addComponent(lblCoursesCode)
                        .addGap(63, 63, 63)
                        .addComponent(txtCoursesCode)))
                .addContainerGap())
        );
        pnlCoursesInfoLayout.setVerticalGroup(
            pnlCoursesInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCoursesId)
                .addGap(22, 22, 22)
                .addGroup(pnlCoursesInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCoursesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoursesName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCoursesInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(txtCoursesCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCoursesInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoursesCode)
                    .addComponent(txtCoursesCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCoursesInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRecordButtonSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCoursesInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRecordButtonSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        CoursesController coursesController = new CoursesController();
        coursesController.setCoursesName(txtCoursesName.getText());
        coursesController.setCoursesCredit(Short.parseShort(txtCoursesCredit.getText()));
        coursesController.setCoursesCode(txtCoursesCode.getText());
        
        CoursesDbModel coursesDbModel = new CoursesDbModel();
        coursesDbModel.coursesRecord(coursesController);
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCoursesCode;
    public javax.swing.JLabel lblCoursesId;
    private javax.swing.JLabel lblCoursesName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JPanel pnlCoursesInfo;
    private javax.swing.JPanel pnlRecordButtonSet;
    public javax.swing.JTextField txtCoursesCode;
    public javax.swing.JTextField txtCoursesCredit;
    public javax.swing.JTextField txtCoursesName;
    // End of variables declaration//GEN-END:variables
}
