/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author gurkay
 */
public class FrmMain extends javax.swing.JFrame {
    
    IntFrmAddPersonal intFrmAddPersonal;
    IntFrmAddCourses intFrmAddCourses;
    IntFrmAddCoursePlaning intFrmAddCoursePlaning;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAddAll = new javax.swing.JMenu();
        menuAddPersonal = new javax.swing.JMenuItem();
        menuAddCourses = new javax.swing.JMenuItem();
        menuAddCoursePlans = new javax.swing.JMenuItem();
        menuListAll = new javax.swing.JMenu();
        menuListPersonals = new javax.swing.JMenuItem();
        menuListCourses = new javax.swing.JMenuItem();
        menuListCoursePlans = new javax.swing.JMenuItem();
        menuReportAll = new javax.swing.JMenu();
        menuReportTakeCourseAllPersonals = new javax.swing.JMenuItem();
        menuReportNotTakeCourseAllPersonals = new javax.swing.JMenuItem();
        menuReportPublishCourses = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jDesktopPane, java.awt.BorderLayout.CENTER);

        menuAddAll.setText("Ekleme İşlemleri");

        menuAddPersonal.setText("Personel Ekle");
        menuAddPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddPersonalActionPerformed(evt);
            }
        });
        menuAddAll.add(menuAddPersonal);

        menuAddCourses.setText("Kurs Ekle");
        menuAddCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCoursesActionPerformed(evt);
            }
        });
        menuAddAll.add(menuAddCourses);

        menuAddCoursePlans.setText("Kurs Planla");
        menuAddCoursePlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCoursePlansActionPerformed(evt);
            }
        });
        menuAddAll.add(menuAddCoursePlans);

        jMenuBar1.add(menuAddAll);

        menuListAll.setText("Listeleme İşlemleri");

        menuListPersonals.setText("Personel Listesi");
        menuListPersonals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListPersonalsActionPerformed(evt);
            }
        });
        menuListAll.add(menuListPersonals);

        menuListCourses.setText("Kurs Listesi");
        menuListCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListCoursesActionPerformed(evt);
            }
        });
        menuListAll.add(menuListCourses);

        menuListCoursePlans.setText("Kurs Plan Listesi");
        menuListCoursePlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListCoursePlansActionPerformed(evt);
            }
        });
        menuListAll.add(menuListCoursePlans);

        jMenuBar1.add(menuListAll);

        menuReportAll.setText("Raporlama İşlemleri");

        menuReportTakeCourseAllPersonals.setText("Kurs Almış Personel");
        menuReportTakeCourseAllPersonals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportTakeCourseAllPersonalsActionPerformed(evt);
            }
        });
        menuReportAll.add(menuReportTakeCourseAllPersonals);

        menuReportNotTakeCourseAllPersonals.setText("Kurs Almamış Personel");
        menuReportNotTakeCourseAllPersonals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportNotTakeCourseAllPersonalsActionPerformed(evt);
            }
        });
        menuReportAll.add(menuReportNotTakeCourseAllPersonals);

        menuReportPublishCourses.setText("Yayınlanan Kurslar");
        menuReportPublishCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportPublishCoursesActionPerformed(evt);
            }
        });
        menuReportAll.add(menuReportPublishCourses);

        jMenuBar1.add(menuReportAll);

        menuExit.setText("Çıkış");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAddPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddPersonalActionPerformed
        
        if (intFrmAddPersonal == null || intFrmAddPersonal.isClosed()) {
            intFrmAddPersonal = new IntFrmAddPersonal();
            jDesktopPane.add(intFrmAddPersonal);
            intFrmAddPersonal.setVisible(true);
        } else {
            intFrmAddPersonal.setLocation(this.getWidth()/2-intFrmAddPersonal.getWidth()/2, 
                    this.getHeight()/2-intFrmAddPersonal.getHeight()/2);
            intFrmAddPersonal.setVisible(true);
        }
        
    }//GEN-LAST:event_menuAddPersonalActionPerformed

    private void menuAddCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCoursesActionPerformed
        if (intFrmAddCourses == null || intFrmAddCourses.isClosed()) {
            intFrmAddCourses = new IntFrmAddCourses();
            jDesktopPane.add(intFrmAddCourses);
            intFrmAddCourses.setVisible(true);
        } else {
            intFrmAddCourses.setLocation(this.getWidth()/2-intFrmAddCourses.getWidth()/2, 
                    this.getHeight()/2-intFrmAddCourses.getHeight()/2);
            intFrmAddCourses.setVisible(true);
        }
    }//GEN-LAST:event_menuAddCoursesActionPerformed

    private void menuAddCoursePlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCoursePlansActionPerformed
        if (intFrmAddCoursePlaning == null || intFrmAddCoursePlaning.isClosed()) {
            intFrmAddCoursePlaning = new IntFrmAddCoursePlaning();
            jDesktopPane.add(intFrmAddCoursePlaning);
            intFrmAddCoursePlaning.setVisible(true);
        } else {
            intFrmAddCoursePlaning.setLocation(this.getWidth()/2-intFrmAddCoursePlaning.getWidth()/2, 
                    this.getHeight()/2-intFrmAddCoursePlaning.getHeight()/2);
            intFrmAddCoursePlaning.setVisible(true);
        }
    }//GEN-LAST:event_menuAddCoursePlansActionPerformed

    private void menuListPersonalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListPersonalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListPersonalsActionPerformed

    private void menuListCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListCoursesActionPerformed

    private void menuListCoursePlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListCoursePlansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListCoursePlansActionPerformed

    private void menuReportTakeCourseAllPersonalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportTakeCourseAllPersonalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportTakeCourseAllPersonalsActionPerformed

    private void menuReportNotTakeCourseAllPersonalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportNotTakeCourseAllPersonalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportNotTakeCourseAllPersonalsActionPerformed

    private void menuReportPublishCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportPublishCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportPublishCoursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAddAll;
    private javax.swing.JMenuItem menuAddCoursePlans;
    private javax.swing.JMenuItem menuAddCourses;
    private javax.swing.JMenuItem menuAddPersonal;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuListAll;
    private javax.swing.JMenuItem menuListCoursePlans;
    private javax.swing.JMenuItem menuListCourses;
    private javax.swing.JMenuItem menuListPersonals;
    private javax.swing.JMenu menuReportAll;
    private javax.swing.JMenuItem menuReportNotTakeCourseAllPersonals;
    private javax.swing.JMenuItem menuReportPublishCourses;
    private javax.swing.JMenuItem menuReportTakeCourseAllPersonals;
    // End of variables declaration//GEN-END:variables
}
