/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Collections.CllGlobal;
import Collections.CllNavigationButton;
import Models.MdlPersonal;
import Models.MdlRank;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gurkay
 */
public class IntFrmAddPersonal extends javax.swing.JInternalFrame {
    
    CllNavigationButton cllNavigationButton = new CllNavigationButton();

    /**
     * Creates new form IntFrmAddPersonal
     */
    public IntFrmAddPersonal() {

        initComponents();

        for (int i = 0; i < CllGlobal.cmbBoxCity.length; i++) {
            cmbCity.addItem(CllGlobal.cmbBoxCity[i]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxBranch.length; i++) {
            cmbBranch.addItem(CllGlobal.cmbBoxBranch[i]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxClass.length; i++) {
            cmbClass.addItem(CllGlobal.cmbBoxClass[i]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxStatus.length; i++) {
            cmbStatus.addItem(CllGlobal.cmbBoxStatus[i][1]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxRank.length; i++) {
            cmbRank.addItem(CllGlobal.cmbBoxRank[i]);
        }

        for (String cmbBoxRegisterDate : CllGlobal.cmbBoxRegisterDate) {
            cmbRegisterDate.addItem(cmbBoxRegisterDate);
        }

        MyItemListener actionListener = new MyItemListener();
        cmbStatus.addItemListener(actionListener);
        
        cllNavigationButton.refreshButton("refreshButtonIntFrmAddPersonal");
    }

    class MyItemListener implements ItemListener {

        public void itemStateChanged(ItemEvent evt) {

            String query = null;
            JComboBox cmbBoxRank = (JComboBox) evt.getSource();

            Object item = evt.getItem();

            if (evt.getStateChange() == ItemEvent.SELECTED) {
                cmbRank.removeAllItems();
                MdlRank mdlRank = new MdlRank();
                switch (cmbBoxRank.getItemAt(cmbBoxRank.getSelectedIndex()).toString()) {
                    case "Subay":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 1;
                        break;
                    case "Astsubay":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 2;
                        break;
                    case "Jandarma Uzman Çavuş":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 3;
                        break;
                    case "Jandarma Uzman Erbaş":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 4;
                        break;
                }
                List<Object[]> result = mdlRank.selectRank(query);

                String arrayHeader[] = {"Rank ID", "Rank Name", "Status ID"};
                DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);

                for (Object[] rank : result) {
                    table.addRow(rank);
                }

                CllGlobal.cmbBoxRank = new String[table.getRowCount()];

                for (int i = 0; i < table.getRowCount(); i++) {
                    CllGlobal.cmbBoxRank[i] = table.getValueAt(i, 1).toString();
                }

                for (int i = 0; i < CllGlobal.cmbBoxRank.length; i++) {
                    cmbRank.addItem(CllGlobal.cmbBoxRank[i]);
                }

            } else if (evt.getStateChange() == ItemEvent.DESELECTED) {

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPersonalInfo = new javax.swing.JPanel();
        cmbCity = new javax.swing.JComboBox<>();
        cmbBranch = new javax.swing.JComboBox<>();
        cmbClass = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbRank = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        txtPersonalID = new javax.swing.JTextField();
        lblTC = new javax.swing.JLabel();
        txtTC = new javax.swing.JTextField();
        lblPbik = new javax.swing.JLabel();
        txtPbik = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblRegister = new javax.swing.JLabel();
        txtRegister = new javax.swing.JTextField();
        lblTask = new javax.swing.JLabel();
        txtTask = new javax.swing.JTextField();
        lblContinent = new javax.swing.JLabel();
        txtContinent = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblRank = new javax.swing.JLabel();
        scrPnlPersonal = new javax.swing.JScrollPane();
        tblPersonal = new javax.swing.JTable();
        lblSearchTC = new javax.swing.JLabel();
        txtSearchPbik = new javax.swing.JTextField();
        lblRegister1 = new javax.swing.JLabel();
        cmbRegisterDate = new javax.swing.JComboBox<>();
        btnSearchPbik = new javax.swing.JButton();
        pnlNavigator = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(92, 236, 182));
        setClosable(true);

        pnlPersonalInfo.setBackground(new java.awt.Color(124, 203, 237));

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cmbRank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        lblID.setText("ID");

        txtPersonalID.setEditable(false);

        lblTC.setText("T.C.");

        lblPbik.setText("Pbik");

        lblFirstName.setText("Ad");

        lblLastName.setText("Soyad");

        lblRegister.setText("Sicili");

        lblTask.setText("Görevi");

        lblContinent.setText("Kıtası");

        txtContinent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContinentActionPerformed(evt);
            }
        });

        lblCity.setText("Şehir");

        lblBranch.setText("Branş");

        lblClass.setText("Sınıf");

        lblStatus.setText("Statüsü");

        lblRank.setText("Rütbe");

        scrPnlPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrPnlPersonalMouseClicked(evt);
            }
        });

        tblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonalMouseClicked(evt);
            }
        });
        scrPnlPersonal.setViewportView(tblPersonal);

        lblSearchTC.setText("Pbik Göre Ara");

        txtSearchPbik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchPbikKeyReleased(evt);
            }
        });

        lblRegister1.setText("Sicil Tarihi");

        cmbRegisterDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        btnSearchPbik.setText("Bul");
        btnSearchPbik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPbikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPersonalInfoLayout = new javax.swing.GroupLayout(pnlPersonalInfo);
        pnlPersonalInfo.setLayout(pnlPersonalInfoLayout);
        pnlPersonalInfoLayout.setHorizontalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPbik, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegister, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTask, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContinent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBranch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRank, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBranch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContinent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPbik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(txtPersonalID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblRegister1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRank, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblSearchTC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchPbik, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchPbik)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrPnlPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPersonalInfoLayout.setVerticalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchPbik, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cmbRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPersonalID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID)
                            .addComponent(lblSearchTC)
                            .addComponent(lblRegister1)
                            .addComponent(btnSearchPbik))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTC)
                            .addComponent(txtTC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPbik)
                            .addComponent(txtPbik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegister)
                            .addComponent(txtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTask)
                            .addComponent(txtTask, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContinent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(lblContinent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(lblCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(lblBranch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(lblClass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(lblStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRank)
                            .addComponent(cmbRank, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)))
                    .addComponent(scrPnlPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNavigator.setBackground(new java.awt.Color(137, 181, 209));

        btnNew.setText("Yeni");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Kaydet");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Güncelle");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Yenile");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Sil");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigatorLayout = new javax.swing.GroupLayout(pnlNavigator);
        pnlNavigator.setLayout(pnlNavigatorLayout);
        pnlNavigatorLayout.setHorizontalGroup(
            pnlNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavigatorLayout.setVerticalGroup(
            pnlNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (txtPersonalID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lütfen Silinecek personel seçiniz");
        } else {
            cllNavigationButton.deleteButton("deleteButtonIntFrmAddPersonal");
            cllNavigationButton.newButton("newButtonIntFrmAddPersonal");
            cllNavigationButton.refreshButton("refreshButtonIntFrmAddPersonal");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtPbik.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pbik giriniz");
        } else {
            cllNavigationButton.saveButton("saveButtonIntFrmAddPersonal");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        cllNavigationButton.newButton("newButtonIntFrmAddPersonal");
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtContinentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContinentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContinentActionPerformed

    private void txtSearchPbikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchPbikKeyReleased
        //String query = txtSearchPbik.getText().toLowerCase();
        //filter(query);
    }//GEN-LAST:event_txtSearchPbikKeyReleased

    private void tblPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonalMouseClicked
        try {

            int selectedRow = tblPersonal.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblPersonal.getModel();

            MdlPersonal mdlPersonal = new MdlPersonal();
            String query = "SELECT p.id, p.pbik, p.tc, p.first_name, p.last_name, c.class_name, r.rank_name, b.branch_name, p.register, p.register_date, p.task, p.continent, ci.city_name, s.status_name "
                    + "FROM personal p "
                    + "JOIN class c ON c.class_id = p.class_id "
                    + "JOIN rank r ON r.rank_id = p.rank_id "
                    + "JOIN branch b ON b.branch_id = p.branch_id "
                    + "JOIN city ci ON ci.city_id = p.city_id "
                    + "JOIN status s ON s.status_id = p.status_id "
                    + "WHERE p.pbik = " + Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

            List<Object[]> result = mdlPersonal.selectPersonal("selectTablePersonal", query);

            String arrayHeader[] = {"ID", "Pbik", "TC", "First Name", "Last Name", "Class", "Rank", "Branch", "Register", "Register Date", "Task", "Continent", "City", "Status"};
            DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);
            for (Object[] personal : result) {
                table.addRow(personal);
            }
            cmbStatus.setSelectedItem(table.getValueAt(0, 13).toString());
            txtPersonalID.setText(table.getValueAt(0, 0).toString());
            txtPbik.setText(table.getValueAt(0, 1).toString());
            txtTC.setText(table.getValueAt(0, 2).toString());
            txtFirstName.setText(table.getValueAt(0, 3).toString());
            txtLastName.setText(table.getValueAt(0, 4).toString());
            for (int i = 0; i < cmbClass.getItemCount(); i++) {
                if (table.getValueAt(0, 5).toString().equals(cmbClass.getItemAt(i).toString())) {
                    cmbClass.setSelectedItem(table.getValueAt(0, 5).toString());
                }
            }
            /**
             *
             * RANK SET
             *
             */
            cmbRank.removeAllItems();
            MdlRank mdlRank = new MdlRank();
            switch (table.getValueAt(0, 13).toString()) {
                case "Subay":
                    query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 1;
                    break;
                case "Astsubay":
                    query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 2;
                    break;
                case "Jandarma Uzman Çavuş":
                    query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 3;
                    break;
                case "Jandarma Uzman Erbaş":
                    query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 4;
                    break;
            }

            List<Object[]> rslt = mdlRank.selectRank(query);

            String arrayHdr[] = {"Rank ID", "Rank Name", "Status ID"};
            DefaultTableModel tbl = new DefaultTableModel(arrayHdr, 0);

            for (Object[] rank : rslt) {
                tbl.addRow(rank);
            }

            for (int i = 0; i < tbl.getRowCount(); i++) {
                cmbRank.addItem(tbl.getValueAt(i, 1).toString());
            }

            cmbRank.setSelectedItem(table.getValueAt(0, 6).toString());
            cmbBranch.setSelectedItem(table.getValueAt(0, 7).toString());
            txtRegister.setText(table.getValueAt(0, 8).toString());
            cmbRegisterDate.setSelectedItem(table.getValueAt(0, 9).toString());
            txtTask.setText(table.getValueAt(0, 10).toString());
            txtContinent.setText(table.getValueAt(0, 11).toString());
            cmbCity.setSelectedItem(table.getValueAt(0, 12).toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getStackTrace());
        }
    }//GEN-LAST:event_tblPersonalMouseClicked

    private void scrPnlPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrPnlPersonalMouseClicked

    }//GEN-LAST:event_scrPnlPersonalMouseClicked

    private void btnSearchPbikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPbikActionPerformed
        cllNavigationButton.searchButton("searchButtonIntFrmAddPersonal");
    }//GEN-LAST:event_btnSearchPbikActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        cllNavigationButton.refreshButton("refreshButtonIntFrmAddPersonal");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtPbik.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pbik giriniz");
        } else {
            cllNavigationButton.updateButton("updateButtonIntFrmAddPersonal");            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchPbik;
    private javax.swing.JButton btnUpdate;
    public static javax.swing.JComboBox<String> cmbBranch;
    public static javax.swing.JComboBox<String> cmbCity;
    public static javax.swing.JComboBox<String> cmbClass;
    public static javax.swing.JComboBox<String> cmbRank;
    public static javax.swing.JComboBox<String> cmbRegisterDate;
    public static javax.swing.JComboBox<String> cmbStatus;
    public static javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblContinent;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPbik;
    private javax.swing.JLabel lblRank;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRegister1;
    private javax.swing.JLabel lblSearchTC;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTC;
    private javax.swing.JLabel lblTask;
    private javax.swing.JPanel pnlNavigator;
    private javax.swing.JPanel pnlPersonalInfo;
    public static javax.swing.JScrollPane scrPnlPersonal;
    public static javax.swing.JTable tblPersonal;
    public static javax.swing.JTextField txtContinent;
    public static javax.swing.JTextField txtFirstName;
    public static javax.swing.JTextField txtLastName;
    public static javax.swing.JTextField txtPbik;
    public static javax.swing.JTextField txtPersonalID;
    public static javax.swing.JTextField txtRegister;
    public static javax.swing.JTextField txtSearchPbik;
    public static javax.swing.JTextField txtTC;
    public static javax.swing.JTextField txtTask;
    // End of variables declaration//GEN-END:variables
}
