/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Collections.*;
import Models.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author gurkay
 */
public class IntFrmAddCoursePlaning extends javax.swing.JInternalFrame {

    CllNavigationButton cllNavigationButton = new CllNavigationButton();
    CllOperationsOfDate cllOperationsOfDate = new CllOperationsOfDate();
    CllAddCoursePlaning cllAddCoursePlaning = new CllAddCoursePlaning();
    

    /**
     * Creates new form IntFrmAddCoursePlaning
     */
    public IntFrmAddCoursePlaning() {
        initComponents();

        for (int i = 0; i < CllGlobal.cmbBoxCity.length; i++) {
            cmbCity.addItem(CllGlobal.cmbBoxCity[i]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxBranch.length; i++) {
            cmbBranch.addItem(CllGlobal.cmbBoxBranch[i]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxClass.length; i++) {
            cmbClass.addItem(CllGlobal.cmbBoxClass[i]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxStatus.length; i++) {
            cmbStatus.addItem(CllGlobal.cmbBoxStatus[i][1]);
        }

        for (int i = 0; i < CllGlobal.cmbBoxRank.length; i++) {
            cmbRank.addItem(CllGlobal.cmbBoxRank[i]);
        }

        MyItemListener actionListener = new MyItemListener();
        cmbStatus.addItemListener(actionListener);

        cllNavigationButton.refreshButton("refreshButtonIntFrmAddCoursePlaning");

    }

    class MyItemListener implements ItemListener {

        public void itemStateChanged(ItemEvent evt) {

            String query = null;
            JComboBox cmbBoxRank = (JComboBox) evt.getSource();

            Object item = evt.getItem();

            if (evt.getStateChange() == ItemEvent.SELECTED) {
                cmbRank.removeAllItems();
                MdlRank mdlRank = new MdlRank();
                switch (cmbBoxRank.getItemAt(cmbBoxRank.getSelectedIndex()).toString()) {
                    case "Subay":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 1;
                        break;
                    case "Astsubay":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 2;
                        break;
                    case "Jandarma Uzman Çavuş":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 3;
                        break;
                    case "Jandarma Uzman Erbaş":
                        query = "SELECT r.rank_id, r.rank_name, r.status_id FROM rank r WHERE r.status_id = " + 4;
                        break;
                }
                List<Object[]> result = mdlRank.selectRank(query);

                String arrayHeader[] = {"Rank ID", "Rank Name", "Status ID"};
                DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);

                for (Object[] rank : result) {
                    table.addRow(rank);
                }

                CllGlobal.cmbBoxRank = new String[table.getRowCount()];

                for (int i = 0; i < table.getRowCount(); i++) {
                    CllGlobal.cmbBoxRank[i] = table.getValueAt(i, 1).toString();
                }
                
                cmbRank.addItem("Select");
                for (int i = 0; i < CllGlobal.cmbBoxRank.length; i++) {
                    cmbRank.addItem(CllGlobal.cmbBoxRank[i]);
                }

            } else if (evt.getStateChange() == ItemEvent.DESELECTED) {

            }
        }
    }

    private void querySelect() {
        try {
            if(rdBtnCoursesStatusTake.isSelected()) {
                cllAddCoursePlaning.chkRdBtnCoursesStatusTake(0);
            } else if (rdBtnCoursesStatusNotTake.isSelected()) {
                cllAddCoursePlaning.chkRdBtnCoursesStatusTake(1);
            } else {
                JOptionPane.showMessageDialog(null, "Kurs Durumunu Seçiniz !");
            }     
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getStackTrace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdBtnGroupCoursesStatus = new javax.swing.ButtonGroup();
        pnlCoursePlaning = new javax.swing.JPanel();
        tabCoursePlaning = new javax.swing.JTabbedPane();
        pnlTabSelectCourse = new javax.swing.JPanel();
        pnlCoursesStatusRange1 = new javax.swing.JPanel();
        lblCourseBeginDateFormatted = new javax.swing.JLabel();
        lblCourseEndDateFormatted = new javax.swing.JLabel();
        frmtTxtBeginDate = new javax.swing.JFormattedTextField();
        frmtTxtEndDate = new javax.swing.JFormattedTextField();
        txtCoursesCode = new javax.swing.JTextField();
        txtCoursesID = new javax.swing.JTextField();
        lblCoursesID = new javax.swing.JLabel();
        lblCoursesCode = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCourseBeginDate = new javax.swing.JLabel();
        lblCourseEndDate = new javax.swing.JLabel();
        scrPnlCoursesName = new javax.swing.JScrollPane();
        txtAreaCoursesName = new javax.swing.JTextArea();
        pnlCoursesStatusRange2 = new javax.swing.JPanel();
        scrPnlCourses = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        pnlTabSelectPersonal = new javax.swing.JPanel();
        pnlCoursesStatus = new javax.swing.JPanel();
        rdBtnCoursesStatusTake = new javax.swing.JRadioButton();
        rdBtnCoursesStatusNotTake = new javax.swing.JRadioButton();
        pnlCoursesStatusRange = new javax.swing.JPanel();
        lblCity = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox<>();
        lblBranch = new javax.swing.JLabel();
        cmbBranch = new javax.swing.JComboBox<>();
        lblClass = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        lblRank = new javax.swing.JLabel();
        cmbRank = new javax.swing.JComboBox<>();
        pnlCoursesSearchList = new javax.swing.JPanel();
        scrPnlPersonal = new javax.swing.JScrollPane();
        tblPersonal = new javax.swing.JTable();
        pnlCoursesInfoList = new javax.swing.JPanel();
        lblCourseName1 = new javax.swing.JLabel();
        lblCourseName2 = new javax.swing.JLabel();
        lblCourseBeginDate1 = new javax.swing.JLabel();
        lblCourseBeginDate2 = new javax.swing.JLabel();
        lblCourseEndDate1 = new javax.swing.JLabel();
        lblCourseEndDate2 = new javax.swing.JLabel();
        lblCourseDays = new javax.swing.JLabel();
        lblCourseDays1 = new javax.swing.JLabel();
        pnlCoursesAddPersonalList = new javax.swing.JPanel();
        scrPnlPersonalAdd = new javax.swing.JScrollPane();
        tblPersonalAdd = new javax.swing.JTable();
        btnAddPersonelList = new javax.swing.JButton();
        btnMinusPersonalList = new javax.swing.JButton();
        btnMinusPersonalList1 = new javax.swing.JButton();
        pnlTabPlanOfCourses = new javax.swing.JPanel();
        pnlPlanOfCourses = new javax.swing.JPanel();
        scrPnlCoursePlaningPersonal = new javax.swing.JScrollPane();
        tblCoursePlaningPersonal = new javax.swing.JTable();
        pnlPersonalPlanOfCourses = new javax.swing.JPanel();
        scrPnlCoursePlaning = new javax.swing.JScrollPane();
        tblCoursePlaning = new javax.swing.JTable();
        pnlBtnOk = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        pnlNavigator = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);

        pnlCoursePlaning.setBackground(new java.awt.Color(137, 181, 209));

        tabCoursePlaning.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabCoursePlaningFocusGained(evt);
            }
        });

        pnlCoursesStatusRange1.setBackground(new java.awt.Color(243, 232, 211));
        pnlCoursesStatusRange1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kurs Tarihleri"));

        lblCourseBeginDateFormatted.setText("Örnek : 23.06.2019");

        lblCourseEndDateFormatted.setText("Örnek : 30.06.2019");

        frmtTxtBeginDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        frmtTxtBeginDate.setToolTipText("");
        frmtTxtBeginDate.setMaximumSize(new java.awt.Dimension(160, 28));

        frmtTxtEndDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        frmtTxtEndDate.setMaximumSize(new java.awt.Dimension(160, 28));

        lblCoursesID.setText("Kurs ID");

        lblCoursesCode.setText("Kurs Kodu");

        lblCourseName.setText("Kurs Adı");

        lblCourseBeginDate.setText("Kurs Başlama Tarihi");

        lblCourseEndDate.setText("Kurs Bitiş Tarihi");

        scrPnlCoursesName.setAutoscrolls(true);
        scrPnlCoursesName.setHorizontalScrollBar(null);

        txtAreaCoursesName.setEditable(false);
        txtAreaCoursesName.setColumns(20);
        txtAreaCoursesName.setLineWrap(true);
        txtAreaCoursesName.setRows(5);
        txtAreaCoursesName.setWrapStyleWord(true);
        scrPnlCoursesName.setViewportView(txtAreaCoursesName);

        javax.swing.GroupLayout pnlCoursesStatusRange1Layout = new javax.swing.GroupLayout(pnlCoursesStatusRange1);
        pnlCoursesStatusRange1.setLayout(pnlCoursesStatusRange1Layout);
        pnlCoursesStatusRange1Layout.setHorizontalGroup(
            pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesStatusRange1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseBeginDate)
                            .addComponent(lblCourseEndDate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(lblCoursesID, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblCoursesCode)
                    .addComponent(lblCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCoursesID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoursesCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCoursesStatusRange1Layout.createSequentialGroup()
                        .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frmtTxtBeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frmtTxtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseEndDateFormatted)
                            .addComponent(lblCourseBeginDateFormatted)))
                    .addComponent(scrPnlCoursesName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        pnlCoursesStatusRange1Layout.setVerticalGroup(
            pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoursesStatusRange1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseBeginDateFormatted)
                    .addGroup(pnlCoursesStatusRange1Layout.createSequentialGroup()
                        .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frmtTxtBeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourseBeginDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseEndDate)
                            .addComponent(lblCourseEndDateFormatted)
                            .addComponent(frmtTxtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCoursesID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoursesID))
                .addGap(18, 18, 18)
                .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoursesCode)
                    .addComponent(txtCoursesCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCoursesStatusRange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlCoursesName, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(pnlCoursesStatusRange1Layout.createSequentialGroup()
                        .addComponent(lblCourseName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlCoursesStatusRange2.setBackground(new java.awt.Color(243, 232, 211));
        pnlCoursesStatusRange2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kurslar"));

        scrPnlCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrPnlCoursesMouseClicked(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCoursesMouseClicked(evt);
            }
        });
        scrPnlCourses.setViewportView(tblCourses);

        javax.swing.GroupLayout pnlCoursesStatusRange2Layout = new javax.swing.GroupLayout(pnlCoursesStatusRange2);
        pnlCoursesStatusRange2.setLayout(pnlCoursesStatusRange2Layout);
        pnlCoursesStatusRange2Layout.setHorizontalGroup(
            pnlCoursesStatusRange2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(pnlCoursesStatusRange2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCoursesStatusRange2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrPnlCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlCoursesStatusRange2Layout.setVerticalGroup(
            pnlCoursesStatusRange2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlCoursesStatusRange2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCoursesStatusRange2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrPnlCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnlTabSelectCourseLayout = new javax.swing.GroupLayout(pnlTabSelectCourse);
        pnlTabSelectCourse.setLayout(pnlTabSelectCourseLayout);
        pnlTabSelectCourseLayout.setHorizontalGroup(
            pnlTabSelectCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabSelectCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCoursesStatusRange2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCoursesStatusRange1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTabSelectCourseLayout.setVerticalGroup(
            pnlTabSelectCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabSelectCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabSelectCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCoursesStatusRange2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCoursesStatusRange1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabCoursePlaning.addTab("Kurs Seçimi", pnlTabSelectCourse);

        pnlCoursesStatus.setBackground(new java.awt.Color(243, 232, 211));
        pnlCoursesStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Kurs Durumu"));

        rdBtnGroupCoursesStatus.add(rdBtnCoursesStatusTake);
        rdBtnCoursesStatusTake.setText("Kurs Almış Personel");
        rdBtnCoursesStatusTake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdBtnCoursesStatusTakeMouseClicked(evt);
            }
        });
        rdBtnCoursesStatusTake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnCoursesStatusTakeActionPerformed(evt);
            }
        });

        rdBtnGroupCoursesStatus.add(rdBtnCoursesStatusNotTake);
        rdBtnCoursesStatusNotTake.setText("Kurs Almamış Personel");
        rdBtnCoursesStatusNotTake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdBtnCoursesStatusNotTakeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCoursesStatusLayout = new javax.swing.GroupLayout(pnlCoursesStatus);
        pnlCoursesStatus.setLayout(pnlCoursesStatusLayout);
        pnlCoursesStatusLayout.setHorizontalGroup(
            pnlCoursesStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdBtnCoursesStatusTake)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdBtnCoursesStatusNotTake)
                .addContainerGap())
        );
        pnlCoursesStatusLayout.setVerticalGroup(
            pnlCoursesStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoursesStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnCoursesStatusTake)
                    .addComponent(rdBtnCoursesStatusNotTake))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCoursesStatusRange.setBackground(new java.awt.Color(243, 232, 211));
        pnlCoursesStatusRange.setBorder(javax.swing.BorderFactory.createTitledBorder("Personel Sorgu Kriterleri"));

        lblCity.setText("Şehir");

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        lblBranch.setText("Branş");

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmbBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBranchActionPerformed(evt);
            }
        });

        lblClass.setText("Sınıf");

        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClassActionPerformed(evt);
            }
        });

        lblStatus.setText("Statüsü");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmbStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbStatusFocusLost(evt);
            }
        });
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        lblRank.setText("Rütbe");

        cmbRank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmbRank.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbRankFocusLost(evt);
            }
        });
        cmbRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCoursesStatusRangeLayout = new javax.swing.GroupLayout(pnlCoursesStatusRange);
        pnlCoursesStatusRange.setLayout(pnlCoursesStatusRangeLayout);
        pnlCoursesStatusRangeLayout.setHorizontalGroup(
            pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesStatusRangeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBranch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClass, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBranch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoursesStatusRangeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoursesStatusRangeLayout.createSequentialGroup()
                        .addComponent(lblRank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbRank, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoursesStatusRangeLayout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCoursesStatusRangeLayout.setVerticalGroup(
            pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesStatusRangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranch)
                    .addComponent(cmbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClass)
                    .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoursesStatusRangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRank)
                    .addComponent(cmbRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCoursesSearchList.setBackground(new java.awt.Color(243, 232, 211));
        pnlCoursesSearchList.setBorder(javax.swing.BorderFactory.createTitledBorder("Bulunan Personel"));

        scrPnlPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrPnlPersonalMouseClicked(evt);
            }
        });

        tblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pbik", "TC", "Rütbe", "Ad", "Soyad"
            }
        ));
        tblPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonalMouseClicked(evt);
            }
        });
        scrPnlPersonal.setViewportView(tblPersonal);

        javax.swing.GroupLayout pnlCoursesSearchListLayout = new javax.swing.GroupLayout(pnlCoursesSearchList);
        pnlCoursesSearchList.setLayout(pnlCoursesSearchListLayout);
        pnlCoursesSearchListLayout.setHorizontalGroup(
            pnlCoursesSearchListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPnlPersonal)
        );
        pnlCoursesSearchListLayout.setVerticalGroup(
            pnlCoursesSearchListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesSearchListLayout.createSequentialGroup()
                .addComponent(scrPnlPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCoursesInfoList.setBackground(new java.awt.Color(243, 232, 211));
        pnlCoursesInfoList.setBorder(javax.swing.BorderFactory.createTitledBorder("Kurs Bilgileri"));

        lblCourseName1.setText("Kurs Adı:");

        lblCourseName2.setText("Kurs Adı");

        lblCourseBeginDate1.setText("Kurs Başlama Tarihi:");

        lblCourseBeginDate2.setText("Kurs Başlama Tarihi");

        lblCourseEndDate1.setText("Kurs Bitiş Tarihi:");

        lblCourseEndDate2.setText("Kurs Bitiş Tarihi");

        lblCourseDays.setText("Kurs Günü:");

        lblCourseDays1.setText("Kurs Günü");

        javax.swing.GroupLayout pnlCoursesInfoListLayout = new javax.swing.GroupLayout(pnlCoursesInfoList);
        pnlCoursesInfoList.setLayout(pnlCoursesInfoListLayout);
        pnlCoursesInfoListLayout.setHorizontalGroup(
            pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesInfoListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseName1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCourseBeginDate1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCourseEndDate1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCourseDays, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseName2)
                    .addComponent(lblCourseBeginDate2)
                    .addComponent(lblCourseEndDate2)
                    .addComponent(lblCourseDays1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCoursesInfoListLayout.setVerticalGroup(
            pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesInfoListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName1)
                    .addComponent(lblCourseName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseBeginDate1)
                    .addComponent(lblCourseBeginDate2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseEndDate1)
                    .addComponent(lblCourseEndDate2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoursesInfoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseDays)
                    .addComponent(lblCourseDays1)))
        );

        pnlCoursesAddPersonalList.setBackground(new java.awt.Color(243, 232, 211));
        pnlCoursesAddPersonalList.setBorder(javax.swing.BorderFactory.createTitledBorder("Kurs Alacak Personel"));

        scrPnlPersonalAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrPnlPersonalAddMouseClicked(evt);
            }
        });

        tblPersonalAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pbik", "TC", "Rütbe", "Ad", "Soyad"
            }
        ));
        tblPersonalAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonalAddMouseClicked(evt);
            }
        });
        scrPnlPersonalAdd.setViewportView(tblPersonalAdd);

        javax.swing.GroupLayout pnlCoursesAddPersonalListLayout = new javax.swing.GroupLayout(pnlCoursesAddPersonalList);
        pnlCoursesAddPersonalList.setLayout(pnlCoursesAddPersonalListLayout);
        pnlCoursesAddPersonalListLayout.setHorizontalGroup(
            pnlCoursesAddPersonalListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPnlPersonalAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlCoursesAddPersonalListLayout.setVerticalGroup(
            pnlCoursesAddPersonalListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursesAddPersonalListLayout.createSequentialGroup()
                .addComponent(scrPnlPersonalAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAddPersonelList.setText("Ekle ->");
        btnAddPersonelList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonelListActionPerformed(evt);
            }
        });

        btnMinusPersonalList.setText("<- Çıkar");

        btnMinusPersonalList1.setText("Hepsini Çıkar");

        javax.swing.GroupLayout pnlTabSelectPersonalLayout = new javax.swing.GroupLayout(pnlTabSelectPersonal);
        pnlTabSelectPersonal.setLayout(pnlTabSelectPersonalLayout);
        pnlTabSelectPersonalLayout.setHorizontalGroup(
            pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabSelectPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlCoursesSearchList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTabSelectPersonalLayout.createSequentialGroup()
                        .addGroup(pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCoursesStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCoursesInfoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCoursesStatusRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTabSelectPersonalLayout.createSequentialGroup()
                        .addComponent(btnAddPersonelList, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinusPersonalList, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinusPersonalList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlCoursesAddPersonalList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTabSelectPersonalLayout.setVerticalGroup(
            pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabSelectPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTabSelectPersonalLayout.createSequentialGroup()
                        .addComponent(pnlCoursesAddPersonalList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(btnMinusPersonalList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinusPersonalList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddPersonelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlTabSelectPersonalLayout.createSequentialGroup()
                        .addGroup(pnlTabSelectPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlTabSelectPersonalLayout.createSequentialGroup()
                                .addComponent(pnlCoursesInfoList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlCoursesStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnlCoursesStatusRange, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlCoursesSearchList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlCoursesSearchList.getAccessibleContext().setAccessibleName("");
        pnlCoursesSearchList.getAccessibleContext().setAccessibleDescription("");
        pnlCoursesInfoList.getAccessibleContext().setAccessibleName("Kurs Bilgi");
        pnlCoursesAddPersonalList.getAccessibleContext().setAccessibleName("");

        tabCoursePlaning.addTab("Personel Seçimi", pnlTabSelectPersonal);

        pnlTabPlanOfCourses.setBackground(new java.awt.Color(243, 232, 211));
        pnlTabPlanOfCourses.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlPlanOfCourses.setBackground(new java.awt.Color(243, 232, 211));
        pnlPlanOfCourses.setBorder(javax.swing.BorderFactory.createTitledBorder("Kursa Katılan Personel Listesi"));
        pnlPlanOfCourses.setToolTipText("");

        scrPnlCoursePlaningPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrPnlCoursePlaningPersonalMouseClicked(evt);
            }
        });

        tblCoursePlaningPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pbik", "TC", "Rütbe", "Ad", "Soyad"
            }
        ));
        tblCoursePlaningPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCoursePlaningPersonalMouseClicked(evt);
            }
        });
        scrPnlCoursePlaningPersonal.setViewportView(tblCoursePlaningPersonal);

        javax.swing.GroupLayout pnlPlanOfCoursesLayout = new javax.swing.GroupLayout(pnlPlanOfCourses);
        pnlPlanOfCourses.setLayout(pnlPlanOfCoursesLayout);
        pnlPlanOfCoursesLayout.setHorizontalGroup(
            pnlPlanOfCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanOfCoursesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPnlCoursePlaningPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPlanOfCoursesLayout.setVerticalGroup(
            pnlPlanOfCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanOfCoursesLayout.createSequentialGroup()
                .addComponent(scrPnlCoursePlaningPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPersonalPlanOfCourses.setBackground(new java.awt.Color(243, 232, 211));
        pnlPersonalPlanOfCourses.setBorder(javax.swing.BorderFactory.createTitledBorder("Planlanan Kurslar"));

        scrPnlCoursePlaning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrPnlCoursePlaningMouseClicked(evt);
            }
        });

        tblCoursePlaning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "K.Plan ID", "Kurs Adı", "Başlama Tarihi", "Bitiş Tarihi"
            }
        ));
        tblCoursePlaning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCoursePlaningMouseClicked(evt);
            }
        });
        scrPnlCoursePlaning.setViewportView(tblCoursePlaning);

        javax.swing.GroupLayout pnlPersonalPlanOfCoursesLayout = new javax.swing.GroupLayout(pnlPersonalPlanOfCourses);
        pnlPersonalPlanOfCourses.setLayout(pnlPersonalPlanOfCoursesLayout);
        pnlPersonalPlanOfCoursesLayout.setHorizontalGroup(
            pnlPersonalPlanOfCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPersonalPlanOfCoursesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPnlCoursePlaning, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPersonalPlanOfCoursesLayout.setVerticalGroup(
            pnlPersonalPlanOfCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalPlanOfCoursesLayout.createSequentialGroup()
                .addComponent(scrPnlCoursePlaning, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlTabPlanOfCoursesLayout = new javax.swing.GroupLayout(pnlTabPlanOfCourses);
        pnlTabPlanOfCourses.setLayout(pnlTabPlanOfCoursesLayout);
        pnlTabPlanOfCoursesLayout.setHorizontalGroup(
            pnlTabPlanOfCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabPlanOfCoursesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPersonalPlanOfCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlanOfCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabPlanOfCoursesLayout.setVerticalGroup(
            pnlTabPlanOfCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabPlanOfCoursesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabPlanOfCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPersonalPlanOfCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlanOfCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabCoursePlaning.addTab("Planlanan Kurslar", pnlTabPlanOfCourses);

        pnlBtnOk.setBackground(new java.awt.Color(243, 232, 211));
        pnlBtnOk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnOk.setText("Devam");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnOkLayout = new javax.swing.GroupLayout(pnlBtnOk);
        pnlBtnOk.setLayout(pnlBtnOkLayout);
        pnlBtnOkLayout.setHorizontalGroup(
            pnlBtnOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnOkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBtnOkLayout.setVerticalGroup(
            pnlBtnOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBtnOkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNew.setText("Yeni");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Kaydet");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Güncelle");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Yenile");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Sil");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigatorLayout = new javax.swing.GroupLayout(pnlNavigator);
        pnlNavigator.setLayout(pnlNavigatorLayout);
        pnlNavigatorLayout.setHorizontalGroup(
            pnlNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlNavigatorLayout.setVerticalGroup(
            pnlNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCoursePlaningLayout = new javax.swing.GroupLayout(pnlCoursePlaning);
        pnlCoursePlaning.setLayout(pnlCoursePlaningLayout);
        pnlCoursePlaningLayout.setHorizontalGroup(
            pnlCoursePlaningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursePlaningLayout.createSequentialGroup()
                .addGroup(pnlCoursePlaningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabCoursePlaning, javax.swing.GroupLayout.PREFERRED_SIZE, 1207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCoursePlaningLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCoursePlaningLayout.setVerticalGroup(
            pnlCoursePlaningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoursePlaningLayout.createSequentialGroup()
                .addComponent(tabCoursePlaning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoursePlaningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBtnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCoursePlaning, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCoursePlaning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtAreaCoursesName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kurs Adı Giriniz");
        } else {
            
            cllNavigationButton.saveButton("saveButtonIntFrmAddCoursePlaning");
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {
            switch (tabCoursePlaning.getSelectedIndex()) {
                case 0:


                    lblCourseName2.setText(txtAreaCoursesName.getText());
                    lblCourseBeginDate2.setText(frmtTxtBeginDate.getText());
                    lblCourseEndDate2.setText(frmtTxtEndDate.getText());
                    lblCourseDays1.setText(Integer.toString(cllOperationsOfDate.getDaysCountOfCourses(frmtTxtBeginDate.getText(), frmtTxtEndDate.getText())));
                    tabCoursePlaning.setSelectedIndex(tabCoursePlaning.getSelectedIndex() + 1);
                    
                    break;

                case 1:
                    
                    tabCoursePlaning.setSelectedIndex(tabCoursePlaning.getSelectedIndex() + 1);

                    break;

                case 2:
                    
                    tabCoursePlaning.setSelectedIndex(tabCoursePlaning.getSelectedIndex() + 1);
                    
                    break;

                case 3:

                    break;

                default:

            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getStackTrace());
        }


    }//GEN-LAST:event_btnOkActionPerformed

    private void tabCoursePlaningFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabCoursePlaningFocusGained
        //btnOk.setVisible(true);
    }//GEN-LAST:event_tabCoursePlaningFocusGained

    private void btnAddPersonelListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonelListActionPerformed

        TableModel modelTblPersonal = tblPersonal.getModel();
        int[] indexs = tblPersonal.getSelectedRows();
        Object[] row = new Object[5];
        DefaultTableModel modelTblPersonalAdd = (DefaultTableModel) tblPersonalAdd.getModel();
        for (int i = 0; i < indexs.length; i++) {
            row[0] = modelTblPersonal.getValueAt(indexs[i], 0);
            row[1] = modelTblPersonal.getValueAt(indexs[i], 1);
            row[2] = modelTblPersonal.getValueAt(indexs[i], 2);
            row[3] = modelTblPersonal.getValueAt(indexs[i], 3);
            row[4] = modelTblPersonal.getValueAt(indexs[i], 4);
            modelTblPersonalAdd.addRow(row);
        }
    }//GEN-LAST:event_btnAddPersonelListActionPerformed

    private void scrPnlPersonalAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrPnlPersonalAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scrPnlPersonalAddMouseClicked

    private void tblPersonalAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonalAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPersonalAddMouseClicked

    private void scrPnlPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrPnlPersonalMouseClicked

    }//GEN-LAST:event_scrPnlPersonalMouseClicked

    private void tblPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonalMouseClicked

    }//GEN-LAST:event_tblPersonalMouseClicked

    private void cmbRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRankActionPerformed

    }//GEN-LAST:event_cmbRankActionPerformed

    private void cmbRankFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbRankFocusLost
        querySelect();
    }//GEN-LAST:event_cmbRankFocusLost

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed

    }//GEN-LAST:event_cmbStatusActionPerformed

    private void cmbStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbStatusFocusLost
        querySelect();
    }//GEN-LAST:event_cmbStatusFocusLost

    private void cmbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassActionPerformed
        querySelect();
    }//GEN-LAST:event_cmbClassActionPerformed

    private void cmbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchActionPerformed
        querySelect();
    }//GEN-LAST:event_cmbBranchActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        querySelect();
    }//GEN-LAST:event_cmbCityActionPerformed

    private void rdBtnCoursesStatusNotTakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdBtnCoursesStatusNotTakeMouseClicked
        try {
            cllAddCoursePlaning.chkRdBtnCoursesStatusTake(1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getStackTrace());
        }
    }//GEN-LAST:event_rdBtnCoursesStatusNotTakeMouseClicked

    private void rdBtnCoursesStatusTakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnCoursesStatusTakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnCoursesStatusTakeActionPerformed

    private void rdBtnCoursesStatusTakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdBtnCoursesStatusTakeMouseClicked
        try {
            cllAddCoursePlaning.chkRdBtnCoursesStatusTake(0);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getStackTrace());
        }
    }//GEN-LAST:event_rdBtnCoursesStatusTakeMouseClicked

    private void scrPnlCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrPnlCoursesMouseClicked

    }//GEN-LAST:event_scrPnlCoursesMouseClicked

    private void tblCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoursesMouseClicked
        int selectedRow = tblCourses.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();

        MdlCourses mdlCourses = new MdlCourses();
        String query = "SELECT c.courses_id, c.courses_name, c.courses_code FROM courses c "
        + "WHERE c.courses_id = " + Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

        List<Object[]> result = mdlCourses.selectCourses("recordCourses", query);

        String arrayHeader[] = {"ID", "Kurs Adı", "Kurs Kodu"};
        DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);
        for (Object[] temp : result) {
            table.addRow(temp);
        }

        txtCoursesID.setText(table.getValueAt(0, 0).toString());
        txtAreaCoursesName.setText(table.getValueAt(0, 1).toString());
        txtCoursesCode.setText(table.getValueAt(0, 2).toString());
    }//GEN-LAST:event_tblCoursesMouseClicked

    private void tblCoursePlaningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoursePlaningMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCoursePlaningMouseClicked

    private void scrPnlCoursePlaningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrPnlCoursePlaningMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scrPnlCoursePlaningMouseClicked

    private void tblCoursePlaningPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoursePlaningPersonalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCoursePlaningPersonalMouseClicked

    private void scrPnlCoursePlaningPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrPnlCoursePlaningPersonalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scrPnlCoursePlaningPersonalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPersonelList;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMinusPersonalList;
    private javax.swing.JButton btnMinusPersonalList1;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    public static javax.swing.JComboBox<String> cmbBranch;
    public static javax.swing.JComboBox<String> cmbCity;
    public static javax.swing.JComboBox<String> cmbClass;
    public static javax.swing.JComboBox<String> cmbRank;
    public static javax.swing.JComboBox<String> cmbStatus;
    public static javax.swing.JFormattedTextField frmtTxtBeginDate;
    public static javax.swing.JFormattedTextField frmtTxtEndDate;
    public static javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblCourseBeginDate;
    private javax.swing.JLabel lblCourseBeginDate1;
    public static javax.swing.JLabel lblCourseBeginDate2;
    private javax.swing.JLabel lblCourseBeginDateFormatted;
    private javax.swing.JLabel lblCourseDays;
    public static javax.swing.JLabel lblCourseDays1;
    private javax.swing.JLabel lblCourseEndDate;
    private javax.swing.JLabel lblCourseEndDate1;
    public static javax.swing.JLabel lblCourseEndDate2;
    private javax.swing.JLabel lblCourseEndDateFormatted;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseName1;
    public static javax.swing.JLabel lblCourseName2;
    private javax.swing.JLabel lblCoursesCode;
    private javax.swing.JLabel lblCoursesID;
    private javax.swing.JLabel lblRank;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlBtnOk;
    private javax.swing.JPanel pnlCoursePlaning;
    public static javax.swing.JPanel pnlCoursesAddPersonalList;
    private javax.swing.JPanel pnlCoursesInfoList;
    public static javax.swing.JPanel pnlCoursesSearchList;
    private javax.swing.JPanel pnlCoursesStatus;
    private javax.swing.JPanel pnlCoursesStatusRange;
    public static javax.swing.JPanel pnlCoursesStatusRange1;
    private javax.swing.JPanel pnlCoursesStatusRange2;
    private javax.swing.JPanel pnlNavigator;
    private javax.swing.JPanel pnlPersonalPlanOfCourses;
    private javax.swing.JPanel pnlPlanOfCourses;
    private javax.swing.JPanel pnlTabPlanOfCourses;
    private javax.swing.JPanel pnlTabSelectCourse;
    private javax.swing.JPanel pnlTabSelectPersonal;
    private javax.swing.JRadioButton rdBtnCoursesStatusNotTake;
    private javax.swing.JRadioButton rdBtnCoursesStatusTake;
    private javax.swing.ButtonGroup rdBtnGroupCoursesStatus;
    public static javax.swing.JScrollPane scrPnlCoursePlaning;
    public static javax.swing.JScrollPane scrPnlCoursePlaningPersonal;
    public static javax.swing.JScrollPane scrPnlCourses;
    public static javax.swing.JScrollPane scrPnlCoursesName;
    public static javax.swing.JScrollPane scrPnlPersonal;
    public static javax.swing.JScrollPane scrPnlPersonalAdd;
    public static javax.swing.JTabbedPane tabCoursePlaning;
    public static javax.swing.JTable tblCoursePlaning;
    public static javax.swing.JTable tblCoursePlaningPersonal;
    public static javax.swing.JTable tblCourses;
    public static javax.swing.JTable tblPersonal;
    public static javax.swing.JTable tblPersonalAdd;
    private javax.swing.JTextArea txtAreaCoursesName;
    public static javax.swing.JTextField txtCoursesCode;
    public static javax.swing.JTextField txtCoursesID;
    // End of variables declaration//GEN-END:variables
}
